SELECT VENCIMENTO, '|', CAST(SUM(VALOR) AS NUMERIC(18, 2))
FROM (SELECT VENCIMENTO, VALOR
      FROM CRECEBER
               JOIN CONTA C1 ON C1.ID = CRECEBER.ID_CONTA
      WHERE "STATUS" = 0
        AND FIMFREQUENCIA = 0
        AND C1.NOME LIKE '%Salário%'
      UNION
      SELECT VENCIMENTO, -VALOR
      FROM CPAGAR
               JOIN CONTA C2 ON C2.ID = CPAGAR.ID_CONTA
      WHERE "STATUS" = 0
        AND FIMFREQUENCIA = 0
        AND C2.NOME LIKE '%Salário%')
GROUP BY VENCIMENTO
ORDER BY VENCIMENTO;