SELECT tc.DESCRICAO,
       '|',
       c.NOME,
       '|',
       CAST((SELECT COALESCE(SUM(MC2.VALOR * (CASE WHEN MC2.TIPO IN (1, 2) THEN -1 ELSE 1 END)), 0)
             FROM MOVCONTA MC2
             WHERE MC2."DATA" <= CURRENT_DATE
               AND MC2.STATUS <> 31
               AND MC2.ID_CONTA = C.ID) AS NUMERIC(18, 2)) SALDO
FROM CONTA c
         JOIN TIPOCONTA tc ON c.ID_TIPOCONTA = tc.ID
WHERE C.INATIVO = 0
ORDER BY tc.DESCRICAO, C.NOME;